CREATE TABLE Alumno (
  ALU_X_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Persona_PER_X_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(ALU_X_ID, Persona_PER_X_ID),
  INDEX Alumno_FKIndex1(Persona_PER_X_ID)
)
ENGINE=InnoDB;

CREATE TABLE Alumno_has_Escuela (
  Alumno_Persona_PER_X_ID INTEGER UNSIGNED NOT NULL,
  Alumno_ALU_X_ID INTEGER UNSIGNED NOT NULL,
  Escuela_ESC_X_ID INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(Alumno_Persona_PER_X_ID, Alumno_ALU_X_ID, Escuela_ESC_X_ID),
  INDEX Alumno_has_Escuela_FKIndex1(Alumno_ALU_X_ID, Alumno_Persona_PER_X_ID),
  INDEX Alumno_has_Escuela_FKIndex2(Escuela_ESC_X_ID)
)
ENGINE=InnoDB;

CREATE TABLE Asistencias (
  ASI_X_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Alumno_has_Escuela_Escuela_ESC_X_ID INTEGER UNSIGNED NOT NULL,
  Alumno_has_Escuela_Alumno_ALU_X_ID INTEGER UNSIGNED NOT NULL,
  Alumno_has_Escuela_Alumno_Persona_PER_X_ID INTEGER UNSIGNED NOT NULL,
  ASI_F_FECHA DATE NULL,
  PRIMARY KEY(ASI_X_ID),
  INDEX Asistencias_FKIndex1(Alumno_has_Escuela_Alumno_Persona_PER_X_ID, Alumno_has_Escuela_Alumno_ALU_X_ID, Alumno_has_Escuela_Escuela_ESC_X_ID)
)
ENGINE=InnoDB;

CREATE TABLE Escuela (
  ESC_X_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Zona_ZON_X_ID INTEGER UNSIGNED NOT NULL,
  ESC_D_NOMBRE VARCHAR(45) NULL,
  PRIMARY KEY(ESC_X_ID),
  INDEX Escuela_FKIndex1(Zona_ZON_X_ID)
)
ENGINE=InnoDB;

CREATE TABLE Persona (
  PER_X_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  PER_D_NOMBRE VARCHAR(45) NULL,
  PER_D_APELLIDO VARCHAR(45) NULL,
  PER_D_TELEFONO VARCHAR(45) NULL,
  PRIMARY KEY(PER_X_ID)
)
ENGINE=InnoDB;

CREATE TABLE Zona (
  ZON_X_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ZON_D_NOMBRE INTEGER UNSIGNED NULL,
  PRIMARY KEY(ZON_X_ID)
)
ENGINE=InnoDB;